# Site settings
title: Tuning Center Foro
description: 'Tuning Center Foro - pregunta, responde, comparte y aprende sobre tu auto'
url: 'https://chinokiller.github.io'
baseurl: '/tuning-center-foro'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Tuning Center'
  email: tuningcenter@gmail.com
  twitter_username: TuningCenter
  facebook_username: TuningCenter
  github_username:  TuningCenter
  linkedin_username:  TuningCenter

# Build settings
destination: _site
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
